# Generated by Django 5.0.1 on 2024-02-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testart', '0002_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='usefulness',
            field=models.BooleanField(null=True),
        ),
    ]
