# Generated by Django 5.0.1 on 2024-02-29 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testart', '0003_comment_usefulness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='usefulness',
            field=models.BooleanField(null=True, verbose_name='Был ли комментарий полезен?'),
        ),
    ]
